# Generated by Django 4.1.5 on 2023-02-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toyshop', '0002_brand_remove_product_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='toyshop.brand'),
        ),
    ]
