version: '3.11'

services:

  db_1:
    container_name: db_toyshop
    image: postgres:13-alpine
    env_file:
      - ./.env
    volumes:
        - ./db_data:/var/lib/postgresql/data
    ports:
      - 54321:5432
