# Generated by Django 4.1.5 on 2023-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptoys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_url',
            field=models.URLField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='productimages',
            name='base_url',
            field=models.URLField(default=None),
        ),
    ]
