# Generated by Django 4.1.5 on 2023-01-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptoys', '0003_alter_product_image_alter_productimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='base_url',
            field=models.URLField(null=True),
        ),
    ]
